pipelines:
   branches:
     prod:
      - step:
          name: Deploy to Lightsail
          deployment: production
          script:
           - echo "Deploying to production environment"
           - apt-get update && apt-get install -y unzip
           - apt-get install -y openssh-client
           - ssh -i ~/.ssh/config  centos@13.234.144.241
           - pipe: atlassian/ssh-run:0.2.2
             variables:
               SSH_USER: 'centos'
               SERVER: '13.234.144.241'
               COMMAND: '/home/centos/deploy.sh'
                
                
                
